<a href="https://colab.research.google.com/github/ggzlemos/Knn/blob/main/Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Esse notebook implementa o algoritmo Knn. Utilizou-se o dataset de íris para testar a implementação 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
from collections import Counter 

In [ ]:
def distancia_euclidiana(a, b):
  dist = np.sqrt(np.sum((a-b) ** 2))
  return dist

In [ ]:
class Knn:
  def __init__(self, k):
    self.k = k
    self.X_treino = []
    self.y_treino = []

  def treinamento(self, X, y):
    self.X_treino = X
    self.y_treino = y.values

  def prediz(self, X):    
    saida = []
    i = 0       
    for exemplo in X:
      #print(i)
      dists = []
      for x in self.X_treino.values:
        dists.append(distancia_euclidiana(exemplo, x))
      
      
      index = np.argsort(dists)[:self.k]          
      rotulos = [self.y_treino[i][0] for i in index]
     
      vizinho = Counter(rotulos).most_common(1)
     
      saida.append(vizinho[0][0])
    
    return np.array(saida)  

In [ ]:
data = load_iris()
X = pd.DataFrame(data.data)
y = pd.DataFrame(data.target)

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state = 42)
y_teste[0].values

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
classificador = Knn(5)
classificador.treinamento(X_treino, y_treino)


a = classificador.prediz(X_teste.values)
print(a)
acuracia = np.sum(a == y_teste[0]) / len(y_teste.values)

acuracia

[79 90 39 73 80]
[ 48  14  94 114  13]
[ 24  21  64  96 106]
[90 79 86 39 22]
[ 92  12 105  80  54]
[114   7  26  71  14]
[ 88  95 108  89 118]
[ 85  76  87  83 103]
[110  73  68  80   5]
[118 108  25 115  34]
[ 87  83  54  17 109]
[104  55  78  70  32]
[14 26 94  7 23]
[ 55 104  32  51  78]
[98 84 94  8 71]
[ 6 11 90 12 59]
[103  97  76  61 100]
[ 53  65  15 118  47]
[22 93 20 34 36]
[107  50  76 103 109]
[70  3 38 55 78]
[ 42  81 113  59  30]
[33 58 57 35 71]
[107  50 109  17  76]
[37 21 64 19 69]
[ 87  85  76  83 103]
[107 109  50  76 119]
[ 61  97 100 103 119]
[104  55  78  70  32]
[ 55  32  70 104   3]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


1.0